id: task-0072
type: task
title: 建设最小统一 LDVH CLI 入口
status: planned
created: '2026-06-11T00:38:52.200694'
updated: '2026-06-11T00:38:52.200694'
description: ''
source: ''
acceptance: ''
blocked_by: []
deliverables: []
