from __future__ import annotations

import re
from pathlib import Path
from typing import Any

import yaml


FENCE_RE = re.compile(r"```yaml\s*\n(.*?)\n```", re.DOTALL)
HEADING_RE = re.compile(r"^(#{1,6})\s+(.+?)\s*$", re.MULTILINE)
SPEC_PATH_RE = re.compile(r"`((?:specs|ldvh-base)/[^`]+?)`")


class MarkdownSpecError(ValueError):
    """Raised when an LDVH Markdown spec cannot be parsed deterministically."""


def extract_markdown_spec(path: str | Path) -> dict[str, Any]:
    source_path = Path(path)
    raw = source_path.read_text(encoding="utf-8")
    title = _extract_title(raw, source_path)
    yaml_blocks = _extract_yaml_blocks(raw, source_path)
    identity = _extract_identity(yaml_blocks, source_path)
    sections = _extract_sections(raw)
    refs = _extract_path_refs(raw)
    return {
        "source_path": _display_path(source_path),
        "title": title,
        "identity": identity,
        "secondary_identities": _extract_secondary_identities(yaml_blocks),
        "sections": sections,
        "path_refs": refs,
    }


def extract_action_source(path: str | Path) -> dict[str, Any]:
    extracted = extract_markdown_spec(path)
    identity = extracted["identity"]
    spec_id = str(identity.get("spec_id") or "").strip()
    if not spec_id:
        raise MarkdownSpecError("v2_spec.spec_id is required")

    status = str(identity.get("status") or "candidate")
    authority = str(identity.get("authority") or "")
    can_authorize = status == "active" and authority == "active"
    canonical_path = identity.get("canonical_path") or extracted["source_path"]

    related_specs = _as_string_list(identity.get("related_specs"))
    basis = _as_string_list(identity.get("basis"))
    parent_spec = str(identity.get("parent_spec") or "").strip()
    read_targets = [canonical_path, *([parent_spec] if parent_spec else []), *basis, *related_specs]

    source_refs = [{"path": canonical_path, "role": "authority"}]
    for ref in [parent_spec, *basis, *related_specs]:
        if ref and ref != canonical_path:
            source_refs.append({"path": ref, "role": "evidence"})

    return {
        "kind": "spec",
        "id": f"SPEC-{spec_id}",
        "title": identity.get("title") or extracted["title"],
        "status": status,
        "authority": {
            "layer": "rule_authority",
            "can_authorize_actions": can_authorize,
            "notes": "Derived directly from the Markdown v2_spec identity block.",
        },
        "source_refs": source_refs,
        "relations": _relations_from_identity(parent_spec, basis, related_specs),
        "read_plan": [
            {
                "order": index,
                "target": target,
                "reason": _read_reason(index, target, canonical_path),
            }
            for index, target in enumerate(_dedupe(read_targets), start=1)
        ],
        "impact_judgment": _impact_judgment(identity),
        "stop_conditions": [
            "Stop if the Markdown identity block is missing or invalid.",
            "Stop if referenced attachments are treated as independent parent specs.",
            "Stop if an Action Guide is treated as a rule source instead of navigation.",
        ],
        "next_queries": [
            "Which referenced attachments define identity fields or relation types?",
            "Which rules should remain in Markdown and which checks can be generated by Code?",
            "Which downstream specs consume this spec's identity and attachment rules?",
        ],
        "action_hints": [
            "Read the Markdown authority first, then its basis and attachments.",
            "Use extracted structure as navigation only; do not create a per-spec YAML twin.",
        ],
        "md_extract": {
            "source_path": extracted["source_path"],
            "spec_kind": identity.get("spec_kind"),
            "parent_spec": parent_spec,
            "relation": identity.get("relation"),
            "section_count": len(extracted["sections"]),
            "path_ref_count": len(extracted["path_refs"]),
            "code_consumption": _as_string_list(identity.get("code_consumption")),
            "secondary_identities": [
                block["kind"] for block in extracted["secondary_identities"]
            ],
        },
    }


def _extract_title(raw: str, source_path: Path) -> str:
    match = HEADING_RE.search(raw)
    if not match or len(match.group(1)) != 1:
        raise MarkdownSpecError(f"{source_path}: first heading must be a level-1 title")
    return match.group(2).strip()


def _extract_yaml_blocks(raw: str, source_path: Path) -> list[dict[str, Any]]:
    blocks: list[dict[str, Any]] = []
    for match in FENCE_RE.finditer(raw):
        loaded = yaml.safe_load(match.group(1))
        if isinstance(loaded, dict):
            blocks.append(loaded)
    if not blocks:
        raise MarkdownSpecError(f"{source_path}: missing fenced yaml identity block")
    return blocks


def _extract_identity(yaml_blocks: list[dict[str, Any]], source_path: Path) -> dict[str, Any]:
    first = yaml_blocks[0]
    if "v2_spec" not in first:
        raise MarkdownSpecError(f"{source_path}: first yaml block must contain v2_spec")
    identity = first["v2_spec"]
    if not isinstance(identity, dict):
        raise MarkdownSpecError(f"{source_path}: v2_spec must be a mapping")
    return identity


def _extract_secondary_identities(
    yaml_blocks: list[dict[str, Any]]
) -> list[dict[str, Any]]:
    secondary: list[dict[str, Any]] = []
    for block in yaml_blocks[1:]:
        for key, value in block.items():
            if isinstance(value, dict):
                secondary.append({"kind": key, "fields": value})
    return secondary


def _extract_sections(raw: str) -> list[dict[str, Any]]:
    return [
        {"level": len(match.group(1)), "title": match.group(2).strip()}
        for match in HEADING_RE.finditer(raw)
    ]


def _extract_path_refs(raw: str) -> list[str]:
    return _dedupe(match.group(1) for match in SPEC_PATH_RE.finditer(raw))


def _relations_from_identity(
    parent_spec: str, basis: list[str], related_specs: list[str]
) -> list[dict[str, str]]:
    relations: list[dict[str, str]] = []
    if parent_spec:
        relations.append({"type": "inherits", "target": parent_spec})
    for target in basis:
        relations.append({"type": "inherits", "target": target})
    for target in related_specs:
        relations.append({"type": "consumes", "target": target})
    return relations


def _impact_judgment(identity: dict[str, Any]) -> list[str]:
    impact = [
        "Changing the identity block can change Code parsing, navigation, and source back-references.",
        "Changing attachment references can change read plans and downstream schema candidates.",
    ]
    positioning = identity.get("positioning")
    if positioning:
        impact.append(f"Positioning: {positioning}")
    return impact


def _read_reason(index: int, target: str, canonical_path: str) -> str:
    if index == 1 or target == canonical_path:
        return "Read the Markdown authority body first."
    if "/attachments/" in target:
        return "Read the authorized attachment after the parent spec."
    return "Read the upstream basis before acting on this spec."


def _as_string_list(value: Any) -> list[str]:
    if isinstance(value, list):
        return [str(item) for item in value]
    if isinstance(value, str) and value:
        return [value]
    return []


def _dedupe(values: Any) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for value in values:
        item = str(value)
        if item not in seen:
            seen.add(item)
            result.append(item)
    return result


def _display_path(path: Path) -> str:
    parts = path.parts
    if "specs" in parts:
        return str(Path(*parts[parts.index("specs") :]))
    return str(path)
