// Generated by code/tools/generate_workcase_presentation_contract.py.
// Do not edit by hand; specification 21 owns the semantics.

export const WORKCASE_PRESENTATION_CONTRACT_IDENTITY = "workcase-current-snapshot-presentation/1" as const;

export const WORKCASE_CURRENT_PHASES = [
  "human_plan_confirming",
  "plan_revising",
  "executing",
  "controller_checking",
  "independent_reviewing",
  "closure_preparing",
  "human_closure_confirming",
  "termination_preparing"
] as const;

export const WORKCASE_PHASE_PRESENTATION = {
  "human_plan_confirming": {
    "lifecycle_position": "human_plan_confirming",
    "handoff_narrative_key": "gate1_waiting",
    "next_required_control_step": "human_gate_1",
    "progress_group": "plan_confirmation",
    "progress_step": null
  },
  "plan_revising": {
    "lifecycle_position": "plan_revising",
    "handoff_narrative_key": "plan_revision_in_progress",
    "next_required_control_step": "form_current_plan",
    "progress_group": "progressing",
    "progress_step": null
  },
  "executing": {
    "lifecycle_position": "executing",
    "handoff_narrative_key": "item_execution_in_progress",
    "next_required_control_step": "advance_current_work_item",
    "progress_group": "progressing",
    "progress_step": "item_execution"
  },
  "controller_checking": {
    "lifecycle_position": "controller_checking",
    "handoff_narrative_key": "result_projection_preparing",
    "next_required_control_step": "form_complete_result_projection",
    "progress_group": "progressing",
    "progress_step": "controller_self_check"
  },
  "independent_reviewing": {
    "lifecycle_position": "independent_reviewing",
    "handoff_narrative_key": "independent_result_review_in_progress",
    "next_required_control_step": "complete_independent_result_review",
    "progress_group": "progressing",
    "progress_step": "independent_review"
  },
  "closure_preparing": {
    "lifecycle_position": "closure_preparing",
    "handoff_narrative_key": "closure_proposal_preparing",
    "next_required_control_step": "form_closure_proposal",
    "progress_group": "progressing",
    "progress_step": "controller_synthesis"
  },
  "human_closure_confirming": {
    "lifecycle_position": "human_closure_confirming",
    "handoff_narrative_key": "gate2_waiting",
    "next_required_control_step": "human_gate_2",
    "progress_group": "closure_confirmation",
    "progress_step": null
  },
  "termination_preparing": {
    "lifecycle_position": "termination_preparing",
    "handoff_narrative_key": "termination_cleanup_in_progress",
    "next_required_control_step": "termination_cleanup",
    "progress_group": "termination_cleanup",
    "progress_step": null
  }
} as const;

export const WORKCASE_CLOSED_PRESENTATION = {
  "lifecycle_position": "closed",
  "handoff_narrative_key": "closed",
  "next_required_control_step": "none",
  "progress_group": "closed",
  "progress_step": null
} as const;

export const WORKCASE_PRESENTATION_UNRESOLVED_REASONS = [
  "missing_source_content_fingerprint",
  "missing_status",
  "unsupported_status",
  "missing_phase",
  "unexpected_phase",
  "closed_with_phase",
  "invalid_status_phase_combination"
] as const;
